//! Link-time optimization support.
//!
//! With `-flto` the compiler writes a bitcode module where an object file
//! belongs, so there is no section header to record a bitcode path in. Two
//! mechanisms answer that, and [`LtoMode`] chooses between them.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::constants::{DARWIN_SECTION_NAME, DARWIN_SEGMENT_NAME, ELF_SECTION_NAME};
use crate::error::Error;

/// How the wrappers handle a build that enables link-time optimization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum LtoMode {
    /// Compile a marker module naming each translation unit's bitcode and
    /// merge it into the LTO object. Works on every linker and both LTO
    /// flavours, and costs one extra compile per translation unit.
    #[default]
    Marker,
    /// Ask the linker to keep the module its own LTO pipeline merged. Full
    /// LTO only, and the link has to go through the wrapper.
    SaveTemps,
    /// Generate nothing, and say so. The behaviour before #96.
    Skip,
}

impl std::fmt::Display for LtoMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LtoMode::Marker => write!(f, "marker"),
            LtoMode::SaveTemps => write!(f, "save-temps"),
            LtoMode::Skip => write!(f, "skip"),
        }
    }
}

impl std::str::FromStr for LtoMode {
    type Err = Error;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "marker" => Ok(Self::Marker),
            "save-temps" => Ok(Self::SaveTemps),
            "skip" => Ok(Self::Skip),
            other => Err(Error::ConfigError(format!(
                "Unknown lto_mode {other:?}; expected one of: marker, save-temps, skip"
            ))),
        }
    }
}

/// Which flavour of link-time optimization the command line asked for.
///
/// The distinction is not cosmetic: full LTO merges every module into one,
/// which the linker can be asked to save, and ThinLTO deliberately never
/// builds such a module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LtoFlavour {
    /// `-flto`, `-flto=full`.
    Full,
    /// `-flto=thin`.
    Thin,
}

/// Escape a path for use inside an assembler string literal.
fn escape_for_assembler(path: &str) -> String {
    // Backslashes first: escaping quotes first would then double the
    // backslashes this step introduces.
    path.replace('\\', r"\\").replace('"', "\\\"")
}

/// Build the marker translation unit that records `bitcode_filepath`.
///
/// The unit is module-level assembly rather than a `used` global on purpose. A
/// global's string literal carries a NUL terminator that corrupts the
/// newline-separated list, and a `used` const global lands in an *alloc*
/// section while rllvm's `llvm-objcopy` section is not, which makes `ld.bfd`
/// emit two sections with the same name. The directive writes exact bytes with
/// exact flags, so both linkers produce one section.
///
/// The target picks the directive: a bitcode object has no binary format to
/// read, and inspecting the host would be wrong under cross-compilation.
/// Exactly one of `__MACH__` and `__ELF__` is defined for the targets rllvm
/// supports, and both follow `--target=`.
pub fn marker_source(bitcode_filepath: &Path) -> String {
    let path = escape_for_assembler(&bitcode_filepath.to_string_lossy());
    format!(
        r#"/* Generated by rllvm. Records the bitcode path for an LTO object. */
#if defined(__MACH__)
__asm__(".section {DARWIN_SEGMENT_NAME},{DARWIN_SECTION_NAME},regular,no_dead_strip\n.ascii \"{path}\\n\"\n.previous");
#elif defined(__ELF__)
__asm__(".section {ELF_SECTION_NAME},\"\",@progbits\n.ascii \"{path}\\n\"\n.previous");
#else
#error "rllvm: -flto bitcode extraction supports ELF and Mach-O only; set lto_mode = \"skip\""
#endif
"#
    )
}

/// Strips dependency-generation flags from a compile-argument list, for use
/// when compiling the LTO marker.
///
/// `-MD`/`-MF` (and friends) reach `compile_args`, and the marker compile is
/// otherwise the *last writer* of the dependency file they name -- it
/// silently replaces the real prerequisites with the marker's own. The
/// marker has no dependencies of its own to report, so these flags are
/// simply dropped rather than translated.
pub fn marker_compile_args(compile_args: &[String]) -> Vec<String> {
    // Flags that take no argument.
    const NULLARY: &[&str] = &["-M", "-MM", "-MD", "-MMD", "-MG", "-MP"];
    // Flags that take an argument, either as the following token (`-MF
    // file`) or joined into the same one (`-MFfile`).
    const UNARY_PREFIXES: &[&str] = &["-MF", "-MT", "-MQ"];

    let mut result = Vec::with_capacity(compile_args.len());
    let mut args = compile_args.iter();
    while let Some(arg) = args.next() {
        if NULLARY.contains(&arg.as_str()) {
            continue;
        }
        if let Some(&prefix) = UNARY_PREFIXES
            .iter()
            .find(|prefix| arg.starts_with(*prefix))
        {
            if arg == prefix {
                // Separate-token form: the next token is the argument.
                args.next();
            }
            // Otherwise the argument is joined into this same token.
            continue;
        }
        result.push(arg.clone());
    }
    result
}

/// The linker flag that makes an LTO link keep its intermediate modules.
///
/// ld64 has its own spelling. Every ELF linker accepts gold's, including lld:
/// `-Wl,-plugin-opt=save-temps` was measured producing byte-identical file
/// names under ld.lld and ld.bfd.
pub fn save_temps_flag(target_is_darwin: bool) -> &'static str {
    if target_is_darwin {
        "-Wl,-save-temps"
    } else {
        "-Wl,-plugin-opt=save-temps"
    }
}

/// Whether `filename` is the merged module an LTO link saved for `output_name`.
///
/// The last stage before codegen, on both linker families: it is the module
/// the linker actually generated code from, and it is the only stage that
/// exists everywhere. ld64's earliest module is already internalized, while
/// lld and bfd expose a pre-internalize `preopt`, so no earlier stage is
/// comparable across linkers.
pub fn is_saved_module(output_name: &str, filename: &str, target_is_darwin: bool) -> bool {
    if target_is_darwin {
        filename == format!("{output_name}.lto.opt.bc")
    } else {
        // `<output>.<partition>.5.precodegen.bc`, one partition by default and
        // more under `--lto-partitions`.
        filename.starts_with(&format!("{output_name}.")) && filename.ends_with(".precodegen.bc")
    }
}

/// Whether `filename` is a save-temps artifact this link produced.
///
/// Used to clean up after a link rllvm added the flag to. The patterns are the
/// measured ones and deliberately nothing wider: this deletes files, and a
/// user file that merely starts with the output's name must survive.
pub fn is_save_temps_artifact(output_name: &str, filename: &str) -> bool {
    let Some(rest) = filename.strip_prefix(&format!("{output_name}.")) else {
        return false;
    };
    // The module rllvm keeps, under the name rllvm chose.
    if rest == "rllvm.bc" {
        return false;
    }
    matches!(
        rest,
        "lto.bc" | "lto.opt.bc" | "lto.o" | "index.bc" | "index.dot" | "resolution.txt"
    ) || rest.ends_with(".preopt.bc")
        || rest.ends_with(".promote.bc")
        || rest.ends_with(".internalize.bc")
        || rest.ends_with(".import.bc")
        || rest.ends_with(".opt.bc")
        || rest.ends_with(".precodegen.bc")
        || rest.ends_with(".thinlto.o")
        || rest
            .strip_prefix("lto.o")
            .is_some_and(|n| !n.is_empty() && n.chars().all(|c| c.is_ascii_digit()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn lto_mode_defaults_to_marker() {
        assert_eq!(LtoMode::default(), LtoMode::Marker);
    }

    #[test]
    fn lto_mode_round_trips_through_its_documented_spelling() {
        for mode in [LtoMode::Marker, LtoMode::SaveTemps, LtoMode::Skip] {
            let spelled = mode.to_string();
            assert_eq!(spelled.parse::<LtoMode>().unwrap(), mode, "{spelled}");
        }
    }

    #[test]
    fn unknown_lto_mode_is_an_error_not_a_fallback() {
        // A typo must stop the build, not silently disable extraction.
        let err = "marker ".parse::<LtoMode>().unwrap_err();
        assert!(matches!(err, Error::ConfigError(_)));
        assert!(err.to_string().contains("save-temps"), "{err}");
    }

    #[test]
    fn marker_source_escapes_quotes_and_backslashes() {
        // A path is not a safe assembler string literal. An unescaped quote
        // ends the `.ascii` operand and the marker stops compiling.
        let source = marker_source(Path::new(r#"/tmp/we"ird\path.bc"#));
        assert!(source.contains(r#"/tmp/we\"ird\\path.bc"#), "{source}");
    }

    #[test]
    fn marker_source_terminates_the_entry_without_a_nul() {
        // The linker concatenates these sections and the entries are
        // newline-separated. `.asciz` would append a NUL between entries and
        // corrupt the list -- measured, not theorised.
        let source = marker_source(Path::new("/tmp/a.bc"));
        assert!(source.contains(r"\\n"), "no newline terminator: {source}");
        assert!(
            !source.contains(".asciz"),
            "must not NUL-terminate: {source}"
        );
    }

    #[test]
    fn marker_source_covers_both_supported_formats() {
        let source = marker_source(Path::new("/tmp/a.bc"));
        assert!(
            source.contains("__RLLVM,__rllvm_bc,regular,no_dead_strip"),
            "{source}"
        );
        assert!(source.contains(".rllvm_bc,\\\"\\\",@progbits"), "{source}");
        assert!(
            source.contains("#error"),
            "unsupported formats must not compile"
        );
    }

    /// A vector shaped like what `cc`/cargo actually pass: real compile
    /// flags interleaved with the dependency-generation flags that must not
    /// reach the marker compile.
    fn cargo_shaped_compile_args() -> Vec<String> {
        [
            "-I",
            "include",
            "-DFOO=1",
            "-MD",
            "-MP",
            "-MF",
            "target/debug/build/foo-0/out/foo.d",
            "-MT",
            "target/debug/build/foo-0/out/foo.o",
            "-O2",
            "-std=c++17",
        ]
        .into_iter()
        .map(String::from)
        .collect()
    }

    #[test]
    fn marker_compile_args_strips_separate_token_dependency_flags() {
        let filtered = marker_compile_args(&cargo_shaped_compile_args());
        assert_eq!(
            filtered,
            ["-I", "include", "-DFOO=1", "-O2", "-std=c++17"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<String>>(),
            "{filtered:?}"
        );
    }

    #[test]
    fn marker_compile_args_strips_joined_dependency_flags() {
        let compile_args = ["-c", "-MFfoo.d", "-MQfoo.o", "-MTfoo.o", "-O2"]
            .into_iter()
            .map(String::from)
            .collect::<Vec<String>>();
        let filtered = marker_compile_args(&compile_args);
        assert_eq!(
            filtered,
            ["-c", "-O2"]
                .into_iter()
                .map(String::from)
                .collect::<Vec<String>>(),
            "{filtered:?}"
        );
    }

    #[test]
    fn marker_compile_args_leaves_unrelated_flags_untouched() {
        // A pure pass-through when there is nothing to strip -- the function
        // must not just happen to work on inputs shaped like the other tests.
        let compile_args = ["-O2", "-std=c11", "-Wall"]
            .into_iter()
            .map(String::from)
            .collect::<Vec<String>>();
        assert_eq!(marker_compile_args(&compile_args), compile_args);
    }

    #[test]
    fn save_temps_flag_matches_the_linker_family() {
        // ld64 has its own spelling; every ELF linker accepts gold's, and
        // ld.lld and ld.bfd were measured producing identical file names.
        assert_eq!(save_temps_flag(true), "-Wl,-save-temps");
        assert_eq!(save_temps_flag(false), "-Wl,-plugin-opt=save-temps");
    }

    #[test]
    fn saved_module_is_recognised_per_linker() {
        assert!(is_saved_module("prog", "prog.lto.opt.bc", true));
        assert!(!is_saved_module("prog", "prog.lto.bc", true));

        assert!(is_saved_module("prog", "prog.0.5.precodegen.bc", false));
        assert!(!is_saved_module("prog", "prog.0.4.opt.bc", false));
        assert!(!is_saved_module("other", "prog.0.5.precodegen.bc", false));
    }

    #[test]
    fn cleanup_spares_the_module_rllvm_keeps_and_the_user_s_files() {
        // Deleting is destructive, so the patterns are the measured ones and
        // nothing wider.
        for litter in [
            "prog.lto.bc",
            "prog.lto.o",
            "prog.lto.o1",
            "prog.0.0.preopt.bc",
            "prog.0.2.internalize.bc",
            "prog.index.bc",
            "prog.index.dot",
            "prog.resolution.txt",
            "prog.0.thinlto.o",
        ] {
            assert!(is_save_temps_artifact("prog", litter), "{litter}");
        }
        for keep in ["prog.rllvm.bc", "prog.bc", "prog", "prog.c", "progress.bc"] {
            assert!(!is_save_temps_artifact("prog", keep), "{keep}");
        }
    }
}
